# https://github.com/actions-rs/clippy

on: [push, pull_request]
name: "Clippy"
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets
